<div id="newsletter-popup-wrapper" class="chl-popup-wrapper">
    <div id="newsletter-overlay" style="display:none;">
        <div class="row">
            <div class="col-md-12">
                <div class="content-popup"><?php echo $block->getConfig('content');?>
                    <form id="newsletter-validate-popup" class="form subscribe" data-mage-init='{"validation": {}}'>       
                        <div class="field newsletter col-md-8">
                            <div class="control">
                                <input name="newsletter-email" type="email" id="newsletter-popup-email" placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>" data-validate="{required:true, 'validate-email':true}"/>
                            </div>
                        </div>
                    </form>	
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "newsletter_popup": {
                        "component": "Chalhoub_NewsletterPopup/js/newsletter_popup",
                        "ajaxUrl": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getFormActionUrl())) ?>"
                    }
                }
            }
        }
    }
</script>